name: Sample workflow file

on:
  workflow_dispatch:

env:
  name: poseidon0070

jobs:
  say-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"

  say-my-name:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello This is $name"
          echo "Learning GitHub workflow!"
